# coding: utf-8

"""
    Controller APIs

    APIs to act on Nextensio Controller  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: developer@nextensio.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BundleStruct(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'bid': 'str',
        'connectid': 'str',
        'cpodrepl': 'int',
        'name': 'str',
        'services': 'list[str]',
        'gateway': 'str',
        'pod': 'str',
        'shared_key': 'str'
    }

    attribute_map = {
        'bid': 'bid',
        'connectid': 'connectid',
        'cpodrepl': 'cpodrepl',
        'name': 'name',
        'services': 'services',
        'gateway': 'gateway',
        'pod': 'pod',
        'shared_key': 'sharedKey'
    }

    def __init__(self, bid=None, connectid=None, cpodrepl=None, name=None, services=None, gateway=None, pod=None, shared_key=None):  # noqa: E501
        """BundleStruct - a model defined in Swagger"""  # noqa: E501
        self._bid = None
        self._connectid = None
        self._cpodrepl = None
        self._name = None
        self._services = None
        self._gateway = None
        self._pod = None
        self._shared_key = None
        self.discriminator = None
        self.bid = bid
        if connectid is not None:
            self.connectid = connectid
        self.cpodrepl = cpodrepl
        self.name = name
        self.services = services
        if gateway is not None:
            self.gateway = gateway
        self.pod = pod
        if shared_key is not None:
            self.shared_key = shared_key

    @property
    def bid(self):
        """Gets the bid of this BundleStruct.  # noqa: E501


        :return: The bid of this BundleStruct.  # noqa: E501
        :rtype: str
        """
        return self._bid

    @bid.setter
    def bid(self, bid):
        """Sets the bid of this BundleStruct.


        :param bid: The bid of this BundleStruct.  # noqa: E501
        :type: str
        """
        if bid is None:
            raise ValueError("Invalid value for `bid`, must not be `None`")  # noqa: E501

        self._bid = bid

    @property
    def connectid(self):
        """Gets the connectid of this BundleStruct.  # noqa: E501


        :return: The connectid of this BundleStruct.  # noqa: E501
        :rtype: str
        """
        return self._connectid

    @connectid.setter
    def connectid(self, connectid):
        """Sets the connectid of this BundleStruct.


        :param connectid: The connectid of this BundleStruct.  # noqa: E501
        :type: str
        """

        self._connectid = connectid

    @property
    def cpodrepl(self):
        """Gets the cpodrepl of this BundleStruct.  # noqa: E501


        :return: The cpodrepl of this BundleStruct.  # noqa: E501
        :rtype: int
        """
        return self._cpodrepl

    @cpodrepl.setter
    def cpodrepl(self, cpodrepl):
        """Sets the cpodrepl of this BundleStruct.


        :param cpodrepl: The cpodrepl of this BundleStruct.  # noqa: E501
        :type: int
        """
        if cpodrepl is None:
            raise ValueError("Invalid value for `cpodrepl`, must not be `None`")  # noqa: E501

        self._cpodrepl = cpodrepl

    @property
    def name(self):
        """Gets the name of this BundleStruct.  # noqa: E501


        :return: The name of this BundleStruct.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this BundleStruct.


        :param name: The name of this BundleStruct.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def services(self):
        """Gets the services of this BundleStruct.  # noqa: E501


        :return: The services of this BundleStruct.  # noqa: E501
        :rtype: list[str]
        """
        return self._services

    @services.setter
    def services(self, services):
        """Sets the services of this BundleStruct.


        :param services: The services of this BundleStruct.  # noqa: E501
        :type: list[str]
        """
        if services is None:
            raise ValueError("Invalid value for `services`, must not be `None`")  # noqa: E501

        self._services = services

    @property
    def gateway(self):
        """Gets the gateway of this BundleStruct.  # noqa: E501


        :return: The gateway of this BundleStruct.  # noqa: E501
        :rtype: str
        """
        return self._gateway

    @gateway.setter
    def gateway(self, gateway):
        """Sets the gateway of this BundleStruct.


        :param gateway: The gateway of this BundleStruct.  # noqa: E501
        :type: str
        """

        self._gateway = gateway

    @property
    def pod(self):
        """Gets the pod of this BundleStruct.  # noqa: E501


        :return: The pod of this BundleStruct.  # noqa: E501
        :rtype: str
        """
        return self._pod

    @pod.setter
    def pod(self, pod):
        """Sets the pod of this BundleStruct.


        :param pod: The pod of this BundleStruct.  # noqa: E501
        :type: str
        """
        if pod is None:
            raise ValueError("Invalid value for `pod`, must not be `None`")  # noqa: E501

        self._pod = pod

    @property
    def shared_key(self):
        """Gets the shared_key of this BundleStruct.  # noqa: E501


        :return: The shared_key of this BundleStruct.  # noqa: E501
        :rtype: str
        """
        return self._shared_key

    @shared_key.setter
    def shared_key(self, shared_key):
        """Sets the shared_key of this BundleStruct.


        :param shared_key: The shared_key of this BundleStruct.  # noqa: E501
        :type: str
        """

        self._shared_key = shared_key

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BundleStruct, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BundleStruct):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
