# coding: utf-8

"""
    Controller APIs

    APIs to act on Nextensio Controller  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: developer@nextensio.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class KeepaliveReq(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'gateway': 'int',
        'device': 'str',
        'version': 'str',
        'source': 'str'
    }

    attribute_map = {
        'gateway': 'gateway',
        'device': 'device',
        'version': 'version',
        'source': 'source'
    }

    def __init__(self, gateway=None, device=None, version=None, source=None):  # noqa: E501
        """KeepaliveReq - a model defined in Swagger"""  # noqa: E501
        self._gateway = None
        self._device = None
        self._version = None
        self._source = None
        self.discriminator = None
        self.gateway = gateway
        self.device = device
        self.version = version
        self.source = source

    @property
    def gateway(self):
        """Gets the gateway of this KeepaliveReq.  # noqa: E501


        :return: The gateway of this KeepaliveReq.  # noqa: E501
        :rtype: int
        """
        return self._gateway

    @gateway.setter
    def gateway(self, gateway):
        """Sets the gateway of this KeepaliveReq.


        :param gateway: The gateway of this KeepaliveReq.  # noqa: E501
        :type: int
        """
        if gateway is None:
            raise ValueError("Invalid value for `gateway`, must not be `None`")  # noqa: E501

        self._gateway = gateway

    @property
    def device(self):
        """Gets the device of this KeepaliveReq.  # noqa: E501


        :return: The device of this KeepaliveReq.  # noqa: E501
        :rtype: str
        """
        return self._device

    @device.setter
    def device(self, device):
        """Sets the device of this KeepaliveReq.


        :param device: The device of this KeepaliveReq.  # noqa: E501
        :type: str
        """
        if device is None:
            raise ValueError("Invalid value for `device`, must not be `None`")  # noqa: E501

        self._device = device

    @property
    def version(self):
        """Gets the version of this KeepaliveReq.  # noqa: E501


        :return: The version of this KeepaliveReq.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this KeepaliveReq.


        :param version: The version of this KeepaliveReq.  # noqa: E501
        :type: str
        """
        if version is None:
            raise ValueError("Invalid value for `version`, must not be `None`")  # noqa: E501

        self._version = version

    @property
    def source(self):
        """Gets the source of this KeepaliveReq.  # noqa: E501


        :return: The source of this KeepaliveReq.  # noqa: E501
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source):
        """Sets the source of this KeepaliveReq.


        :param source: The source of this KeepaliveReq.  # noqa: E501
        :type: str
        """
        if source is None:
            raise ValueError("Invalid value for `source`, must not be `None`")  # noqa: E501

        self._source = source

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(KeepaliveReq, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, KeepaliveReq):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
