# coding: utf-8

"""
    Controller APIs

    APIs to act on Nextensio Controller  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: developer@nextensio.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TenantUpdate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'easymode': 'bool'
    }

    attribute_map = {
        'id': '_id',
        'name': 'name',
        'easymode': 'easymode'
    }

    def __init__(self, id=None, name=None, easymode=None):  # noqa: E501
        """TenantUpdate - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._easymode = None
        self.discriminator = None
        self.id = id
        self.name = name
        self.easymode = easymode

    @property
    def id(self):
        """Gets the id of this TenantUpdate.  # noqa: E501


        :return: The id of this TenantUpdate.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TenantUpdate.


        :param id: The id of this TenantUpdate.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this TenantUpdate.  # noqa: E501


        :return: The name of this TenantUpdate.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this TenantUpdate.


        :param name: The name of this TenantUpdate.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def easymode(self):
        """Gets the easymode of this TenantUpdate.  # noqa: E501


        :return: The easymode of this TenantUpdate.  # noqa: E501
        :rtype: bool
        """
        return self._easymode

    @easymode.setter
    def easymode(self, easymode):
        """Sets the easymode of this TenantUpdate.


        :param easymode: The easymode of this TenantUpdate.  # noqa: E501
        :type: bool
        """
        if easymode is None:
            raise ValueError("Invalid value for `easymode`, must not be `None`")  # noqa: E501

        self._easymode = easymode

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TenantUpdate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TenantUpdate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
