# coding: utf-8

"""
    Controller APIs

    APIs to act on Nextensio Controller  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: developer@nextensio.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UserAdd(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'uid': 'str',
        'name': 'str',
        'pod': 'int',
        'gateway': 'str'
    }

    attribute_map = {
        'uid': 'uid',
        'name': 'name',
        'pod': 'pod',
        'gateway': 'gateway'
    }

    def __init__(self, uid=None, name=None, pod=None, gateway=None):  # noqa: E501
        """UserAdd - a model defined in Swagger"""  # noqa: E501
        self._uid = None
        self._name = None
        self._pod = None
        self._gateway = None
        self.discriminator = None
        self.uid = uid
        self.name = name
        if pod is not None:
            self.pod = pod
        if gateway is not None:
            self.gateway = gateway

    @property
    def uid(self):
        """Gets the uid of this UserAdd.  # noqa: E501


        :return: The uid of this UserAdd.  # noqa: E501
        :rtype: str
        """
        return self._uid

    @uid.setter
    def uid(self, uid):
        """Sets the uid of this UserAdd.


        :param uid: The uid of this UserAdd.  # noqa: E501
        :type: str
        """
        if uid is None:
            raise ValueError("Invalid value for `uid`, must not be `None`")  # noqa: E501

        self._uid = uid

    @property
    def name(self):
        """Gets the name of this UserAdd.  # noqa: E501


        :return: The name of this UserAdd.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this UserAdd.


        :param name: The name of this UserAdd.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def pod(self):
        """Gets the pod of this UserAdd.  # noqa: E501


        :return: The pod of this UserAdd.  # noqa: E501
        :rtype: int
        """
        return self._pod

    @pod.setter
    def pod(self, pod):
        """Sets the pod of this UserAdd.


        :param pod: The pod of this UserAdd.  # noqa: E501
        :type: int
        """

        self._pod = pod

    @property
    def gateway(self):
        """Gets the gateway of this UserAdd.  # noqa: E501


        :return: The gateway of this UserAdd.  # noqa: E501
        :rtype: str
        """
        return self._gateway

    @gateway.setter
    def gateway(self, gateway):
        """Sets the gateway of this UserAdd.


        :param gateway: The gateway of this UserAdd.  # noqa: E501
        :type: str
        """

        self._gateway = gateway

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UserAdd, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserAdd):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
