# coding: utf-8

"""
    Controller APIs

    APIs to act on Nextensio Controller  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: developer@nextensio.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.attr_struct import AttrStruct  # noqa: E501
from swagger_client.rest import ApiException


class TestAttrStruct(unittest.TestCase):
    """AttrStruct unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAttrStruct(self):
        """Test AttrStruct"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.attr_struct.AttrStruct()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
