# coding: utf-8

"""
    Controller APIs

    APIs to act on Nextensio Controller  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: developer@nextensio.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_admin_group(self):
        """Test case for add_admin_group

        add an admin groups to a tenant  # noqa: E501
        """
        pass

    def test_add_attr_set(self):
        """Test case for add_attr_set

        define a new attribute  # noqa: E501
        """
        pass

    def test_add_bundle(self):
        """Test case for add_bundle

        Add bundle.  # noqa: E501
        """
        pass

    def test_add_bundle_attr(self):
        """Test case for add_bundle_attr

        add tenant bundle attrs  # noqa: E501
        """
        pass

    def test_add_certs(self):
        """Test case for add_certs

        add certificate  # noqa: E501
        """
        pass

    def test_add_clientid(self):
        """Test case for add_clientid

        Add a new clientID for a new nextensio App  # noqa: E501
        """
        pass

    def test_add_cluster_handler(self):
        """Test case for add_cluster_handler

        add gateway cluster to tenant  # noqa: E501
        """
        pass

    def test_add_gateway(self):
        """Test case for add_gateway

        add a gateway  # noqa: E501
        """
        pass

    def test_add_host_attr(self):
        """Test case for add_host_attr

        add tenant host attrs  # noqa: E501
        """
        pass

    def test_add_idp_handler(self):
        """Test case for add_idp_handler

        add identity provider to tenant  # noqa: E501
        """
        pass

    def test_add_keep_alive(self):
        """Test case for add_keep_alive

        Send keepalive from device to controller  # noqa: E501
        """
        pass

    def test_add_mgd_tenant(self):
        """Test case for add_mgd_tenant

        assign a managed tenant to a MSP tenant  # noqa: E501
        """
        pass

    def test_add_policy_handler(self):
        """Test case for add_policy_handler

        add policy  # noqa: E501
        """
        pass

    def test_add_stats_rule_handler(self):
        """Test case for add_stats_rule_handler

        add stats rule  # noqa: E501
        """
        pass

    def test_add_tenant(self):
        """Test case for add_tenant

        add basic info for a tenant  # noqa: E501
        """
        pass

    def test_add_trace_req(self):
        """Test case for add_trace_req

        add trace request  # noqa: E501
        """
        pass

    def test_add_trace_rule_handler(self):
        """Test case for add_trace_rule_handler

        add trace rule  # noqa: E501
        """
        pass

    def test_add_user(self):
        """Test case for add_user

        add user  # noqa: E501
        """
        pass

    def test_add_user_attr(self):
        """Test case for add_user_attr

        add tenant user attrs  # noqa: E501
        """
        pass

    def test_add_user_attr_multiple(self):
        """Test case for add_user_attr_multiple

        add tenant user attrs for multiple users  # noqa: E501
        """
        pass

    def test_add_user_key(self):
        """Test case for add_user_key

        add API key  # noqa: E501
        """
        pass

    def test_addbundle_rule_handler(self):
        """Test case for addbundle_rule_handler

        add bundle rule  # noqa: E501
        """
        pass

    def test_addhost_rule_handler(self):
        """Test case for addhost_rule_handler

        add host rule  # noqa: E501
        """
        pass

    def test_del_admin_group(self):
        """Test case for del_admin_group

        delete an admin group from a tenant  # noqa: E501
        """
        pass

    def test_del_attr_set(self):
        """Test case for del_attr_set

        delete an existing attribute  # noqa: E501
        """
        pass

    def test_del_bundle(self):
        """Test case for del_bundle

        del bundle from the tenant  # noqa: E501
        """
        pass

    def test_del_bundle_rule(self):
        """Test case for del_bundle_rule

        delete bundle rule  # noqa: E501
        """
        pass

    def test_del_cert(self):
        """Test case for del_cert

        delete a certificate  # noqa: E501
        """
        pass

    def test_del_gateway(self):
        """Test case for del_gateway

        delete an unused nextensio gateway  # noqa: E501
        """
        pass

    def test_del_host_attr(self):
        """Test case for del_host_attr

        delete host attrs  # noqa: E501
        """
        pass

    def test_del_host_rule(self):
        """Test case for del_host_rule

        delete host rule  # noqa: E501
        """
        pass

    def test_del_idp_handler(self):
        """Test case for del_idp_handler

        delete an IDP  # noqa: E501
        """
        pass

    def test_del_mgd_tenant(self):
        """Test case for del_mgd_tenant

        remove a managed tenant from a MSP tenant  # noqa: E501
        """
        pass

    def test_del_onboard_logs(self):
        """Test case for del_onboard_logs

        delete onboard logs for a particluar user  # noqa: E501
        """
        pass

    def test_del_policy(self):
        """Test case for del_policy

        delete policy  # noqa: E501
        """
        pass

    def test_del_stats_rule(self):
        """Test case for del_stats_rule

        delete stats rule  # noqa: E501
        """
        pass

    def test_del_tenant(self):
        """Test case for del_tenant

        delete a tenant  # noqa: E501
        """
        pass

    def test_del_tenant_cluster(self):
        """Test case for del_tenant_cluster

        delete host attrs  # noqa: E501
        """
        pass

    def test_del_trace_req(self):
        """Test case for del_trace_req

        delete trace request  # noqa: E501
        """
        pass

    def test_del_user(self):
        """Test case for del_user

        delete a user  # noqa: E501
        """
        pass

    def test_del_user_key(self):
        """Test case for del_user_key

        delete API key  # noqa: E501
        """
        pass

    def test_get_admin_for_groups(self):
        """Test case for get_admin_for_groups

        get all admins of a tenant group  # noqa: E501
        """
        pass

    def test_get_admin_groups(self):
        """Test case for get_admin_groups

        get all admin groups of a tenant  # noqa: E501
        """
        pass

    def test_get_all_bundle_attr(self):
        """Test case for get_all_bundle_attr

        get all bundle attrs  # noqa: E501
        """
        pass

    def test_get_all_bundle_rules(self):
        """Test case for get_all_bundle_rules

        get all bundle rules in a tenant  # noqa: E501
        """
        pass

    def test_get_all_bundles(self):
        """Test case for get_all_bundles

        get all bundles  # noqa: E501
        """
        pass

    def test_get_all_certs(self):
        """Test case for get_all_certs

        get all certificates  # noqa: E501
        """
        pass

    def test_get_all_host_attr(self):
        """Test case for get_all_host_attr

        get all host attrs  # noqa: E501
        """
        pass

    def test_get_all_host_rules(self):
        """Test case for get_all_host_rules

        get all host rules in a tenant  # noqa: E501
        """
        pass

    def test_get_all_idps(self):
        """Test case for get_all_idps

        get all IDPs for a tenant  # noqa: E501
        """
        pass

    def test_get_all_policies(self):
        """Test case for get_all_policies

        get all policies in a tenant  # noqa: E501
        """
        pass

    def test_get_all_stats_rules(self):
        """Test case for get_all_stats_rules

        get all stats rules in a tenant  # noqa: E501
        """
        pass

    def test_get_all_tenant_cluster(self):
        """Test case for get_all_tenant_cluster

        get all clusters assigned for a tenant  # noqa: E501
        """
        pass

    def test_get_all_trace_reqs(self):
        """Test case for get_all_trace_reqs

        get info about all trace requests  # noqa: E501
        """
        pass

    def test_get_all_trace_rules(self):
        """Test case for get_all_trace_rules

        get all trace rules in a tenant  # noqa: E501
        """
        pass

    def test_get_all_user_attr(self):
        """Test case for get_all_user_attr

        get all user attrs  # noqa: E501
        """
        pass

    def test_get_all_users(self):
        """Test case for get_all_users

        get all the users of a tenant  # noqa: E501
        """
        pass

    def test_get_attr_collection_hdr(self):
        """Test case for get_attr_collection_hdr

        get the header of an attributes collection for a tenant  # noqa: E501
        """
        pass

    def test_get_bundle(self):
        """Test case for get_bundle

        get bundle info of a tenant  # noqa: E501
        """
        pass

    def test_get_bundle_attr(self):
        """Test case for get_bundle_attr

        get bundle attrs  # noqa: E501
        """
        pass

    def test_get_bundle_status(self):
        """Test case for get_bundle_status

        get the status of every instance of a specific AppGroup extender for a tenant  # noqa: E501
        """
        pass

    def test_get_cert(self):
        """Test case for get_cert

        get a certificate  # noqa: E501
        """
        pass

    def test_get_client_id(self):
        """Test case for get_client_id

        get the clientid providing the proper key/password  # noqa: E501
        """
        pass

    def test_get_gateways(self):
        """Test case for get_gateways

        lists all gateways  # noqa: E501
        """
        pass

    def test_get_host_attr(self):
        """Test case for get_host_attr

        get host attrs  # noqa: E501
        """
        pass

    def test_get_mgd_tenant(self):
        """Test case for get_mgd_tenant

        get all tenant  # noqa: E501
        """
        pass

    def test_get_policy(self):
        """Test case for get_policy

        get policy given the policyid  # noqa: E501
        """
        pass

    def test_get_tenant(self):
        """Test case for get_tenant

        get a tenant  # noqa: E501
        """
        pass

    def test_get_tenant_cluster(self):
        """Test case for get_tenant_cluster

        get the  gateway information (nextensio internal) for a gateway assined to a tenant  # noqa: E501
        """
        pass

    def test_get_tenant_gateways(self):
        """Test case for get_tenant_gateways

        lists all gateways allocated for a tenant  # noqa: E501
        """
        pass

    def test_get_tenants(self):
        """Test case for get_tenants

        get all tenant  # noqa: E501
        """
        pass

    def test_get_trace_req(self):
        """Test case for get_trace_req

        get info about a trace request  # noqa: E501
        """
        pass

    def test_get_trace_requests_hdr(self):
        """Test case for get_trace_requests_hdr

        get the header of a trace requests collection for a tenant  # noqa: E501
        """
        pass

    def test_get_user(self):
        """Test case for get_user

        get a user  # noqa: E501
        """
        pass

    def test_get_user_admin_role(self):
        """Test case for get_user_admin_role

        get the admin role of a user  # noqa: E501
        """
        pass

    def test_get_user_attr(self):
        """Test case for get_user_attr

        get user attrs  # noqa: E501
        """
        pass

    def test_get_user_keys(self):
        """Test case for get_user_keys

        get all the API keys in the tenant  # noqa: E501
        """
        pass

    def test_get_user_onboard_log(self):
        """Test case for get_user_onboard_log

        get a user's onboarding info  # noqa: E501
        """
        pass

    def test_get_user_status(self):
        """Test case for get_user_status

        get details about user devices and their status  # noqa: E501
        """
        pass

    def test_modify_tenant(self):
        """Test case for modify_tenant

        add or modify a tenant  # noqa: E501
        """
        pass

    def test_onboard(self):
        """Test case for onboard

        onboard a nextensio extender  # noqa: E501
        """
        pass

    def test_signup(self):
        """Test case for signup

        allows a user to signup  # noqa: E501
        """
        pass

    def test_upd_tenant_type(self):
        """Test case for upd_tenant_type

        change the type of a tenant  # noqa: E501
        """
        pass

    def test_upd_user_role(self):
        """Test case for upd_user_role

        assign a new role for a user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
