# coding: utf-8

"""
    Controller APIs

    APIs to act on Nextensio Controller  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: developer@nextensio.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.user_keys import UserKeys  # noqa: E501
from swagger_client.rest import ApiException


class TestUserKeys(unittest.TestCase):
    """UserKeys unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserKeys(self):
        """Test UserKeys"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.user_keys.UserKeys()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
