/*
 * Controller APIs
 *
 * APIs to act on Nextensio Controller
 *
 * API version: 1.0.0
 * Contact: development@nextensio.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type HostRule struct {
	Host string `json:"host"`
	Rid string `json:"rid"`
	Group string `json:"group"`
	Rule [][]string `json:"rule"`
}
