/*
 * Controller APIs
 *
 * APIs to act on Nextensio Controller
 *
 * API version: 1.0.0
 * Contact: developer@nextensio.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UserAdd struct {
	Uid string `json:"uid"`
	Name string `json:"name"`
	Pod int32 `json:"pod,omitempty"`
	Gateway string `json:"gateway,omitempty"`
}
