/*
 * Controller APIs
 *
 * APIs to act on Nextensio Controller
 *
 * API version: 1.0.0
 * Contact: developer@nextensio.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type KeepaliveReq struct {
	Gateway int32 `json:"gateway"`
	Device string `json:"device"`
	Version string `json:"version"`
	Source string `json:"source"`
}
