/*
 * Controller APIs
 *
 * APIs to act on Nextensio Controller
 *
 * API version: 1.0.0
 * Contact: developer@nextensio.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AttrSetStruct struct {
	Name string `json:"name"`
	AppliesTo string `json:"appliesTo"`
	Type_ string `json:"type"`
	IsArray string `json:"isArray"`
	Group string `json:"group"`
}
