/*
 * Controller APIs
 *
 * APIs to act on Nextensio Controller
 *
 * API version: 1.0.0
 * Contact: developer@nextensio.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TraceRule struct {
	Rid string `json:"rid"`
	Group string `json:"group"`
	Rule [][]string `json:"rule"`
}
