/*
 * Controller APIs
 *
 * APIs to act on Nextensio Controller
 *
 * API version: 1.0.0
 * Contact: development@nextensio.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GetPolicyStruct struct {
	Result string `json:"Result"`
	Pid string `json:"pid"`
	Rego []int32 `json:"rego"`
}
