/*
 * Controller APIs
 *
 * APIs to act on Nextensio Controller
 *
 * API version: 1.0.0
 * Contact: developer@nextensio.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type OnboardLogDetails struct {
	Result string `json:"Result"`
	Gw string `json:"gw"`
	Pod int32 `json:"pod"`
	Podnm string `json:"podnm"`
	Connectid string `json:"connectid"`
	Onbtime string `json:"onbtime"`
	Count int32 `json:"count"`
	Prevtime string `json:"prevtime"`
}
