/*
 * Controller APIs
 *
 * APIs to act on Nextensio Controller
 *
 * API version: 1.0.0
 * Contact: developer@nextensio.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AddIdp struct {
	Provider string `json:"provider"`
	Name string `json:"name"`
	Policy string `json:"policy"`
	Domain string `json:"domain"`
	Group string `json:"group"`
	Auth string `json:"auth"`
	Jwks string `json:"jwks"`
	Token string `json:"token"`
	Issuer string `json:"issuer"`
	Sso string `json:"sso"`
	Audience string `json:"audience"`
	Client string `json:"client"`
	Secret string `json:"secret"`
	Cert string `json:"cert"`
	Keyid string `json:"keyid"`
}
