/*
 * Controller APIs
 *
 * APIs to act on Nextensio Controller
 *
 * API version: 1.0.0
 * Contact: developer@nextensio.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TenantUpdate struct {
	Id string `json:"_id"`
	Name string `json:"name"`
	Easymode bool `json:"easymode,omitempty"`
}
