/*
 * Controller APIs
 *
 * APIs to act on Nextensio Controller
 *
 * API version: 1.0.0
 * Contact: development@nextensio.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GatewayStruct struct {
	Name string `json:"name"`
	Location string `json:"location"`
	Zone string `json:"zone"`
	Region string `json:"region"`
	Provider string `json:"provider"`
}
