/*
 * Controller APIs
 *
 * APIs to act on Nextensio Controller
 *
 * API version: 1.0.0
 * Contact: development@nextensio.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SignupDetails struct {
	Tenant string `json:"tenant"`
	Email string `json:"email"`
	Ismsp bool `json:"ismsp"`
}
