/*
 * Controller APIs
 *
 * APIs to act on Nextensio Controller
 *
 * API version: 1.0.0
 * Contact: development@nextensio.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DataHdr struct {
	Name string `json:"name,omitempty"`
	AppliesTo string `json:"appliesTo,omitempty"`
	Type_ string `json:"type,omitempty"`
	IsArray string `json:"isArray,omitempty"`
	Group string `json:"group,omitempty"`
}
